<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\eng\Versions.props" />

  <PropertyGroup>
	<TargetFramework>$(DefaultNetCoreTargetFramework)</TargetFramework>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\.keys\GrappDefaultKey.pfx</AssemblyOriginatorKeyFile>
    <DelaySign>false</DelaySign>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <AssemblyName>Corex.Exceptions</AssemblyName>
    <RootNamespace>Corex.Exceptions</RootNamespace>
    <LangVersion>latest</LangVersion>
    <PackageTags>Exception, Flow Exception, Library</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <PackageProjectUrl>https://github.com/adrianosepe/Corex</PackageProjectUrl>
    <PackageIcon> </PackageIcon>
    <RepositoryUrl>https://github.com/adrianosepe/Corex</RepositoryUrl>
    <RepositoryType>GitHub</RepositoryType>
    <PackageReleaseNotes>Full GrappTec dependencies published to NuGet.</PackageReleaseNotes>
    <Version>1.0.0</Version>
    <Authors>Adriano Sepe</Authors>
    <Company>GrappTec</Company>
    <Description>General purpose exception library.</Description>
	<Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Manager\Resources\EmailErrorContent.html" />
    <None Remove="Manager\Resources\ExceptionContent.html" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Manager\Resources\EmailErrorContent.html" />
    <EmbeddedResource Include="Manager\Resources\ExceptionContent.html" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2023.2.0" />
  </ItemGroup>

</Project>
